const yargs = require('yargs') // NPM Module
const fs = require('fs') // Node Module
const chalk = require('chalk');
const notes = require('./notes.js') // Local Module
const l = console.log
const fs = require('fs');
error = chalk.white.bgRed.bold('ERROR ');
errMsg = chalk.red.italic;
success = chalk.white.bgGreen.bold('SUCCESS ');
sucMsg = chalk.green.italic;